dist: bionic

language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run $(bash <(curl -s https://codecov.io/env)) app sh -c "pytest --cov=./ && flake8 && codecov"